# Generated by Django 2.1.15 on 2022-03-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('idnumber', models.CharField(db_column='idnumber', max_length=9)),
                ('fname', models.TextField(db_column='fname')),
                ('lname', models.TextField(db_column='lname')),
                ('bday', models.DateField(db_column='bday')),
                ('type', models.TextField(db_column='type')),
                ('address', models.TextField(db_column='address')),
                ('city', models.TextField(db_column='city')),
                ('country', models.TextField(db_column='country')),
                ('phone', models.CharField(db_column='phone', max_length=11)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('idnumber', models.CharField(db_column='idnumber', max_length=9)),
                ('fname', models.TextField(db_column='fname')),
                ('lname', models.TextField(db_column='lname')),
            ],
            options={
                'db_table': 'director',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pharmacian',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('idnumber', models.CharField(db_column='idnumber', max_length=9)),
                ('fname', models.TextField(db_column='fname')),
                ('lname', models.TextField(db_column='lname')),
            ],
            options={
                'db_table': 'pharmacian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('idnumber', models.CharField(db_column='idnumber', max_length=9)),
                ('fname', models.TextField(db_column='fname')),
                ('lname', models.TextField(db_column='lname')),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
