# Generated by Django 3.2.6 on 2022-05-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeSce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('idnumber', models.CharField(db_column='idnumber', max_length=11)),
                ('password', models.TextField(db_column='password')),
                ('fname', models.TextField(db_column='fname')),
                ('lname', models.TextField(db_column='lname')),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordered',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('cid', models.IntegerField()),
                ('wid', models.IntegerField(blank=True, db_column='wid', null=True)),
                ('total', models.DecimalField(db_column='total', decimal_places=2, max_digits=10)),
                ('status', models.TextField(db_column='status')),
            ],
            options={
                'db_table': 'ordered',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordershop',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('cid', models.IntegerField(db_column='cid')),
                ('pid', models.TextField(db_column='pid')),
                ('quantity', models.IntegerField(db_column='quantity')),
            ],
            options={
                'db_table': 'ordershop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('pid', models.IntegerField(db_column='pid')),
                ('informations', models.TextField(db_column='informations')),
            ],
            options={
                'db_table': 'prescription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('supplier', models.TextField(db_column='supplier')),
                ('type', models.TextField(db_column='type')),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(db_column='stock')),
                ('prescription', models.TextField(db_column='prescription')),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('idnumber', models.CharField(db_column='idnumber', max_length=11)),
                ('password', models.TextField(db_column='password')),
                ('fname', models.TextField(db_column='fname')),
                ('lname', models.TextField(db_column='lname')),
            ],
            options={
                'db_table': 'worker',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Pharmacian',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
